name: 'SFTP Transfer'
description: 'Connect to SFTP Server and Transfer Local Files'
inputs:
  server: 
    description: 'Server name secret'
    required: true
    default: ''
  user:  
    description: 'Username secret'
    required: true
    default: ''
  pass:  
    description: 'Password secret'
    required: true
    default: ''
  port:  
    description: 'Port'
    required: true
    default: '22'
  local-path:  
    description: 'Local Path'
    required: true
    default: '/'
  remote-path:  
    description: 'Remote Path'
    required: true
    default: '/'
outputs:
  directory:
    description: 'Directory List'
runs:
  using: 'node12'
  main: 'dist/index.js'