on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SFTP Transfer Test
    steps:
    - name: Connect
      id: connect
      uses: danhendrickson/sftp-transfer-action@v1
      with:
        server: '68.183.103.230'
        user: 'adenbrook-api'
        pass: '4H#M$KT232k*926x'
        port: '22'
        local-path: './'
        remote-path: '/public_html/'
    # Use the output from the `hello` step
    - name: List Directory
      run: echo "The time was ${{ steps.connect.outputs.directory }}"
