on: [push]

jobs:
  sftp_transfer_job:
    runs-on: ubuntu-latest
    name: SFTP Transfer Test
    steps:
    - uses: actions/checkout@v1

    - name: Connect
      id: connect
      uses: danhendrickson/sftp-transfer-action@v1.1
      env:
        server: ${{ secrets.AB_DEV_SERVER }}
        user: ${{ secrets.AB_DEV_SERVER_USER }}
        pass: ${{ secrets.AB_DEV_SERVER_PASS }}
        port: ${{ secrets.AB_DEV_SERVER_PORT }}
        local-path: './'
        remote-path: '/public_html/'

    - name: List Directory
      run: echo "The time was ${{ steps.connect.with.directory }}"
